name: Lint & Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint_and_test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
      - name: Test
        run: go test ./...
