name: Lint & Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint_and_test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - name: Test
        run: go test ./...
